### ISSUE TITLE
Reduction of options for FixMethod

### ISSUE THREAD

**Issue by jeff-saupe** [jeff-saupe/ScheduleCleaner#16]
For the moment we have four different options for FixMethod:

`CONTAINS, EQUALS, ENDS_WITH, STARTS_WITH`

I'm thinking about removing this option, so we'd just stick with `CONTAINS` as the only method for matching Strings. It would reduce the complexity for the user and I can't really think about any use-case for `EQUALS, ENDS_WITH` and `STARTS_WITH` which could not be solved with `CONTAINS`.

What do you think about this?

**Comment by jeff-saupe** [comment]
This would mean that we delete this class and any occurrence in the code and replace it with `CONTAINS`.

**Comment by coderesting** [comment]
I mentioned in #5 that CONTAINS could work with a regex. This would preserve the functionality but I see some issues with overwhelming the user. When we put this functionality in it's own method e.g REGEX there are two methods again  and the class has to stay. I'm not sure what the way to go is.

**Comment by jeff-saupe** [comment]
Yes, I'd offer a great functionality to the user, but as you said it might be overwhelming for the **average** user. We should try to keep it as simple as possible.

And for the moment, I can't think about any situation where `EQUALS, ENDS_WITH `and `STARTS_WITH` could not be solved by using `CONTAINS`. Maybe you have a situation in mind where this removing this functionality would be crucial. Otherwise, I'd propose removing this class.

**Comment by coderesting** [comment]
I can't think of any crucial uses either. Removing it should be alright👍
