### ISSUE TITLE
Possibility to configure the title for classes

### ISSUE THREAD

**Issue by phlpp77** [jeff-saupe/ScheduleCleaner#47]
It would be handy to have the ability to configure the layout of the title used for the cleaned schedule. For E.g. The name **and** the module number are needed "W118 Controlling" instead of just "Controlling". 

I understand that normally you want to reduce as much as possible but sometimes the option for more configuration would be great.

**Comment by jeff-saupe** [comment]
Hey, thanks for your input. :)

This shouldn't be difficult to implement - I think you can expect this feature for the coming weekend.
